.PHONY : all

all: deploy

API_PORT := 8888
APP_NAME := cnema-0.0.1-SNAPSHOT
TARGET_FOLDER := target
JAR_FILE := $(TARGET_FOLDER)/${APP_NAME}.jar
DB_HOST := localhost
DB_PORT := 5432
DB_USERNAME := cnema
DB_PASSWORD := cnema
DB_NAME := cnema
JWT_SECRET := 123456E89765432456786543F6786543245678932473238472348F4124124E
JWT_EXPIRATION := 8640000
CLIENT_KEY := {your-midtrans-client-key}
SERVER_KEY := {your-midtrans-server-key}
clean:
	@echo "Remove existing app $(APP_NAME)..."
	@rm -rf $(TARGET_FOLDER)

build: clean
	@echo "Building Spring Boot app with Maven..."
	@DB_HOST=$(DB_HOST) DB_PORT=$(DB_PORT) DB_USERNAME=$(DB_USERNAME) DB_PASSWORD=$(DB_PASSWORD) DB_NAME=$(DB_NAME) JWT_SECRET=$(JWT_SECRET) JWT_EXPIRATION=$(JWT_EXPIRATION) CLIENT_KEY=$(CLIENT_KEY) SERVER_KEY=$(SERVER_KEY) mvn clean package -DskipTest

deploy: build
	@echo "Building Spring Boot app with Maven..."
	@DB_HOST=$(DB_HOST) DB_PORT=$(DB_PORT) DB_USERNAME=$(DB_USERNAME) DB_PASSWORD=$(DB_PASSWORD) DB_NAME=$(DB_NAME) JWT_SECRET=$(JWT_SECRET) JWT_EXPIRATION=$(JWT_EXPIRATION) CLIENT_KEY=$(CLIENT_KEY) SERVER_KEY=$(SERVER_KEY) java -jar $(JAR_FILE)
