apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnema-pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage # storage punya digital ocean (BELUM DIUBAH)